# Generated by Django 3.2.7 on 2021-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author_id',
            field=models.IntegerField(null=True),
        ),
    ]
