# Generated by Django 3.2.7 on 2021-09-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posts_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.author'),
        ),
    ]
